INSERT INTO "Product" (
  name,
  slug,
  description,
  price,
  "precioBase",
  images,
  stock,
  "categoryId",
  subcategory,
  grupo,
  published,
  featured,
  "createdAt",
  "updatedAt",
  proveedor,
  ref_proveedor,
  ref_variante,
  ean,
  marca,
  categoria_texto,
  categoria_padre,
  color,
  talla,
  activo,
  visible_web,
  sku_interno
) VALUES (
  '{{ $json.name.replace(/'/g, "''") }}',
  '{{ $json.slug.replace(/'/g, "''") }}',
  '{{ $json.description.replace(/'/g, "''") }}',
  ROUND(({{ $json.precioBase }}::numeric * CASE WHEN {{ $json.precioBase }} < 50 THEN 1.50 WHEN {{ $json.precioBase }} < 100 THEN 1.47 WHEN {{ $json.precioBase }} < 200 THEN 1.43 WHEN {{ $json.precioBase }} < 400 THEN 1.38 ELSE 1.30 END * 1.21), 2),
  {{ $json.precioBase }},
  {{ $json.imagenes.length > 0 ? "ARRAY[" + $json.imagenes.map(img => "'" + img.replace(/'/g, "''") + "'").join(",") + "]::text[]" : "ARRAY[]::text[]" }},
  {{ $json.stock }},
  '{{ $json.categoryId }}',
  '{{ ($json.subcategory || "").replace(/'/g, "''") }}',
  {{ $json.grupo ? "'" + String($json.grupo).replace(/'/g, "''") + "'" : "NULL" }},
  {{ $json.published }},
  false,
  NOW(),
  NOW(),
  '{{ $json.proveedor }}',
  '{{ $json.ref_proveedor }}',
  NULL,
  {{ $json.ean ? "'" + $json.ean + "'" : "NULL" }},
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  {{ $json.activo }},
  {{ $json.visible_web }},
  '{{ $json.sku_interno.replace(/'/g, "''") }}'
)
ON CONFLICT (sku_interno)
DO UPDATE SET
  "categoryId" = EXCLUDED."categoryId",
  subcategory = EXCLUDED.subcategory,
  grupo = EXCLUDED.grupo,
  proveedor = EXCLUDED.proveedor,
  ref_proveedor = EXCLUDED.ref_proveedor,
  ref_variante = EXCLUDED.ref_variante,
  ean = EXCLUDED.ean,
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  description = EXCLUDED.description,
  price = ROUND((EXCLUDED."precioBase" * CASE WHEN EXCLUDED."precioBase" < 50 THEN 1.50 WHEN EXCLUDED."precioBase" < 100 THEN 1.47 WHEN EXCLUDED."precioBase" < 200 THEN 1.43 WHEN EXCLUDED."precioBase" < 400 THEN 1.38 ELSE 1.30 END * 1.21)::numeric, 2),
  "precioBase" = EXCLUDED."precioBase",
  images = EXCLUDED.images,
  stock = EXCLUDED.stock,
  published = EXCLUDED.published,
  activo = EXCLUDED.activo,
  visible_web = EXCLUDED.visible_web,
  "updatedAt" = NOW()
RETURNING id;
